// https://en.cppreference.com/w/cpp/named_req/RandomNumberDistribution
#include <random>

#include "random.hpp"

using namespace WarGrey::STEM;

/*************************************************************************************************/
// Members in <random> override the operator '()' to generate value

// non-determinstic generator
static std::random_device rd;

// to seed mersenne twister, similar to srand() with datum better than time(nullptr);
static std::mt19937 random_generator(rd());

/*************************************************************************************************/
int WarGrey::STEM::random_raw() {
    return random_generator();
}

int WarGrey::STEM::random_uniform(int min, int max) {
    // shape data generated by a generator with a distribution for integers in [min, max] 
    std::uniform_int_distribution<> random_dist(min, max);

    return random_dist(random_generator);
}

unsigned int WarGrey::STEM::random_uniform(unsigned int min, unsigned int max) {
    // shape data generated by a generator with a distribution for integers in [min, max] 
    std::uniform_int_distribution<unsigned int> random_dist(min, max);

    return random_dist(random_generator);
}

float WarGrey::STEM::random_uniform(float min, float max) {
    std::uniform_int_distribution<float> random_dist(min, max);

    return random_dist(random_generator);
}

double WarGrey::STEM::random_uniform(double min, double max) {
    std::uniform_int_distribution<double> random_dist(min, max);

    return random_dist(random_generator);
}

bool WarGrey::STEM::random_bernoulli(double p) {
    std::bernoulli_distribution random_dist(p);

    return random_dist(random_generator);
}
